source 'http://gemcutter.org'

gem 'rails',         :git => 'git://github.com/rails/rails.git'
gem 'builder'
gem 'haml',          :git => 'git://github.com/nex3/haml.git'
gem 'compass',       :git => 'git://github.com/chriseppstein/compass.git'
gem 'acts_as_tree',  '>= 0.1.1'
gem 'cancan',        '>= 1.1.1'
gem 'globalize2',    :git => 'git://github.com/starpeak/globalize2.git'


# This should be only enabled when the Rails app is standalone:
# gem 'humpyard',      :git => 'git://github.com/humpyard/humpyard.git'
gem 'sqlite3-ruby',  :require => 'sqlite3'

